---
title: "pmrs_data_assessment_nov"
subtitle:
author: |
   Texas A&M University-Corpus Christi
output:
    github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(skimr)
```

```{r}
data <- read_xlsx(here::here("data", "raw", "pmar1_survey_data_november_2023.xlsx")) %>%
  janitor::clean_names() %>%
  mutate(across(everything(), as.character)) %>%
  mutate(salinity = as.numeric(salinity)) %>%
  mutate(temp = as.numeric(temp)) %>%
  mutate(do = as.numeric(do)) %>%
  mutate(ph = as.numeric(ph)) %>%
  mutate(total_weight = as.numeric(total_weight)) %>%
  mutate(shell_length = as.numeric(shell_length)) %>%
  mutate(shell_width = as.numeric(shell_width)) %>%
  mutate(shell_height = as.numeric(shell_height)) %>%
  mutate(egg_count = as.numeric(egg_count)) %>%
  mutate(sperm_rating = as.numeric(sperm_rating)) %>%
  mutate(cup_valve_and_meat_weight = as.numeric(cup_valve_and_meat_weight)) %>%
  mutate(flat_valve_weight = as.numeric(flat_valve_weight)) %>%
  mutate(cup_valve_weight = as.numeric(cup_valve_weight))
```

```{r}
skim(data)
str(data)
```

Make shell weight and meat weight column
Make shell weight column
Make meat weight column

```{r}
data <- data %>%
  mutate(shell_weight = flat_valve_weight+cup_valve_weight)%>%
  mutate(meat_weight = cup_valve_and_meat_weight - cup_valve_weight) %>%
  mutate(shell_weight_and_meat_weight = meat_weight + shell_weight) %>%
  select(-cup_valve_and_meat_weight,-flat_valve_weight,-cup_valve_weight) %>%
  select(date,zone,bay,sample_site,salinity,temp,do,ph,tray_num,animal_id,total_weight,shell_length,shell_width,shell_height,plate,well_id,box,tube_id,shell_weight_and_meat_weight,shell_weight,time_shucked,sex,egg_count,sperm_rating,notes)
```

# Save an RDS version

```{r}
saveRDS(data,here::here("data","derived","november_data.rds"))
```

```{r}

```


# Add in other relevant data

## Meat weight

```{r}
data <- data %>%
  mutate(meat_weight = shell_weight_and_meat_weight - shell_weight) %>%
  mutate(wt_adj_fec = egg_count/meat_weight)
```

Look for issues with meat weight

```{r}
hist(data$meat_weight)

plot(data$meat_weight,data$total_weight)
```

Looks good!

# Plot wt_adj_fec

Select females

```{r}
fem <- data %>%
  filter(sex =="F")
```

```{r}
skim(fem)
```

```{r}
ggplot(fem, aes(sample_site,wt_adj_fec)) + 
  geom_boxplot()
```

