---
title: "pmrs_examine_raw_data"
subtitle:
author: |
   Texas A&M University-Corpus Christi
output:
    github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(skimr)
library(RColorBrewer)
```

```{r}
data <- readRDS(here::here("data","derived","clean_data.RDS"))
```

```{r}
str(data)
```

# Data adjustment for graphing

Take out IND data, doesn't add anything

```{r}
data <- data %>%
  filter(!sample_site == "IND")
```

# Number of females 

```{r}
fem <- data %>%
  filter(sex =="F") %>%
  group_by(sample_site,latitude,date,bay) %>%
  summarise(n=n()) %>%
  mutate(latitude = as.numeric(latitude)) %>%
  ungroup()

str(fem)
```

```{r}
ggplot(fem, aes(x = date , y = n, color = latitude,shape = fct_reorder(sample_site,latitude,.desc = TRUE))) +
  geom_point(size = 4) +
  geom_line() + 
  scale_color_gradientn(colors = (brewer.pal(9, "RdYlGn"))) +
  labs(color = "Latitude") + 
  scale_shape_manual(values=seq(0,14)) + 
  theme_dark()
```


```{r}
ggplot(fem, aes(x = date , y = n, color = fct_reorder(bay,latitude, .desc = TRUE),shape = fct_reorder(sample_site,latitude,.desc = TRUE))) +
  geom_point(size = 5) +
  geom_line() + 
  scale_color_brewer(palette = "RdYlGn",direction = -1)+
  labs(color = "Latitude") + 
  scale_shape_manual(values=seq(0,14)) + 
  theme(panel.background = element_rect(fill = "gray70"),  
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "gray"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "gray"))
```


# Wt_spec_fecundity

Filter out outliers to look at later

```{r}
data <- data %>%
  filter(!tube_id == "JAN_UVB_14")
```

```{r}
fec <- data %>%
  filter(sex =="F") %>%
  group_by(sample_site,latitude,date,bay) %>%
  summarise(md=median(wt_adj_fec,na.rm = TRUE)) %>%
  mutate(latitude = as.numeric(latitude)) %>%
  ungroup()

str(fec)
```


```{r}
ggplot(fec, aes(x = date , y = md, color = fct_reorder(bay,latitude, .desc = TRUE),shape = fct_reorder(sample_site,latitude,.desc = TRUE))) +
  geom_point(size = 5) +
  geom_line() + 
  scale_color_brewer(palette = "RdYlGn",direction = -1)+
  labs(color = "Bay",shape = "Site") + 
  scale_shape_manual(values=seq(0,14)) + 
  theme(panel.background = element_rect(fill = "gray70"),  
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "gray"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "gray"))
```


```{r}
ggplot(fec, aes(x = date , y = md, color = fct_reorder(bay,latitude, .desc = TRUE),shape = fct_reorder(sample_site,latitude,.desc = TRUE))) +
  geom_point(size = 5) +
  geom_line() + 
  scale_color_brewer(palette = "RdYlGn",direction = -1)+
  labs(color = "Bay",shape = "Site") + 
      scale_shape_manual(values = c(16, 17)) +  # Use filled shapes, specify only two shapes
      labs(color = "Bay", shape = "Site") + 
      theme(panel.background = element_rect(fill = "white"),  # Change background to white
            panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "gray80"), 
            panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "gray90"),
            legend.background = element_rect(fill = "white", color = "gray80"),  # White legend background
            legend.key = element_rect(fill = "white")) 
```



```{r}
ggplot(fec, aes(x = date, y = md, 
                             color = fct_reorder(bay, latitude, .desc = TRUE),
                             shape = fct_reorder(sample_site, latitude, .desc = TRUE))) +
      geom_point(size = 5, fill = "white", stroke = 1.5) +  # Use filled symbols
      geom_line() + 
      scale_color_brewer(palette = "RdYlGn",direction = -1)+
      scale_shape_manual(values = c(16, 17)) +  # Use filled shapes, specify only two shapes
      labs(color = "Bay", shape = "Site") + 
      theme(panel.background = element_rect(fill = "white"),  # Change background to white
            panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "gray80"), 
            panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "gray90"),
            legend.background = element_rect(fill = "white", color = "gray80"),  # White legend background
            legend.key = element_rect(fill = "white")) 
```


```{r}
look <- data %>%
  filter(sample_site == "UVB") %>%
  filter(date < "2024-02-02")
  
```


```{r}
ggplot(fec, aes(x = date, y = md, color = bay, shape = sample_site)) +
  geom_point(size = 4) + # Adjust size as needed
  scale_shape_manual(values = c(15, 17)) + # 15 = filled square, 17 = filled triangle
  labs(color = "Bay", shape = "Sample Site") +
  theme_minimal()
```

